# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f00436n/engs62/module3/module3/module3.srcs/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0.xci
# IP: The module: 'module3_hw_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module3/module3/module3.gen/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module3_hw_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module3/module3/module3.gen/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module3_hw_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /thayerfs/home/f00436n/engs62/module3/module3/module3.srcs/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0.xci
# IP: The module: 'module3_hw_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module3/module3/module3.gen/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module3_hw_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module3/module3/module3.gen/sources_1/bd/module3_hw/ip/module3_hw_axi_timer_0_0/module3_hw_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module3_hw_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
