# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f00436n/engs62/module5/module5/module5.srcs/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0.xci
# IP: The module: 'module5_hw_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /thayerfs/home/f00436n/engs62/module5/module5/module5.srcs/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0.xci
# IP: The module: 'module5_hw_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module5/module5/module5.gen/sources_1/bd/module5_hw/ip/module5_hw_rst_ps7_0_50M_0/module5_hw_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module5_hw_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
