# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f00436n/engs62/module6/module6/module6.srcs/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1.xci
# IP: The module: 'module6_hw_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /thayerfs/home/f00436n/engs62/module6/module6/module6.srcs/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1.xci
# IP: The module: 'module6_hw_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
