# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /thayerfs/home/f00436n/Xilinx/Zybo-Z7-Master.xdc

# Block Designs: bd/module6_hw/module6_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw || ORIG_REF_NAME==module6_hw} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_processing_system7_0_0/module6_hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_processing_system7_0_0 || ORIG_REF_NAME==module6_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_axi_gpio_0_1/module6_hw_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_axi_gpio_0_1 || ORIG_REF_NAME==module6_hw_axi_gpio_0_1} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_ps7_0_axi_periph_0/module6_hw_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==module6_hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_rst_ps7_0_50M_0/module6_hw_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==module6_hw_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_xbar_0/module6_hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_xbar_0 || ORIG_REF_NAME==module6_hw_xbar_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_axi_gpio_1_0/module6_hw_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_axi_gpio_1_0 || ORIG_REF_NAME==module6_hw_axi_gpio_1_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_axi_gpio_2_0/module6_hw_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_axi_gpio_2_0 || ORIG_REF_NAME==module6_hw_axi_gpio_2_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_xlconcat_0_0/module6_hw_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_xlconcat_0_0 || ORIG_REF_NAME==module6_hw_xlconcat_0_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_axi_timer_0_0/module6_hw_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_axi_timer_0_0 || ORIG_REF_NAME==module6_hw_axi_timer_0_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_xadc_wiz_0_0/module6_hw_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_xadc_wiz_0_0 || ORIG_REF_NAME==module6_hw_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/module6_hw/ip/module6_hw_auto_pc_0/module6_hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module6_hw_auto_pc_0 || ORIG_REF_NAME==module6_hw_auto_pc_0} -quiet] -quiet

# XDC: /thayerfs/home/f00436n/engs62/module6/module6/module6.gen/sources_1/bd/module6_hw/module6_hw_ooc.xdc
