# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f00436n/engs62/module4/module4/module4.srcs/sources_1/bd/module4_hw/ip/module4_hw_xbar_0/module4_hw_xbar_0.xci
# IP: The module: 'module4_hw_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module4/module4/module4.gen/sources_1/bd/module4_hw/ip/module4_hw_xbar_0/module4_hw_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module4_hw_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /thayerfs/home/f00436n/engs62/module4/module4/module4.srcs/sources_1/bd/module4_hw/ip/module4_hw_xbar_0/module4_hw_xbar_0.xci
# IP: The module: 'module4_hw_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f00436n/engs62/module4/module4/module4.gen/sources_1/bd/module4_hw/ip/module4_hw_xbar_0/module4_hw_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module4_hw_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
